### ISSUE TITLE
Checkerboard artifacts

### ISSUE THREAD

**Issue by BuTTerK3ks** [facebookresearch/sapiens#160]
For the depth and normal maps, i get checkerboard artifacts. This seems not to be the case in the example, how can i prevent them?

**Comment by rawalkhirodkar** [comment]
@BuTTerK3ks the artifacts is due to upsampling. If your image resolution is significantly higher or in some cases the due to the deconvolutions used in the head of the model, the artifacts are noticeable.

Consider using smoothing filters on the raw outputs to resolve this. We are working on improving our models in this aspect.
