### ISSUE TITLE
Human video representation

### ISSUE THREAD

**Issue by AmitMY** [facebookresearch/sapiens#183]
I am interested in using sapiens as a strong backbone for sign language tasks.

Your paper says:
> Like all autoencoders, our model has an encoder that maps the visible image to a latent representation and a decoder that reconstructs the original image from this latent representation. Our pretraining dataset consists of both single and multihuman images; each image is resized to a fixed size with a square aspect ratio.

1. I would like to know if I understand correctly - a `1024x1024` image is split into 4096 patches of size `16x16`, and then the encoder outputs 4096 latent representations (no downscaling in the encoder)?

2. Because I can't fit infinite context, I will work (initially) with `128x128` images. Do I understand correctly, that the model takes fixed `1024x1024` images, and so what I will need to do is tile 64 images of size `128x128` if I want such low low res features? Is there another way to feed in a video?

--- 

For the purpose of sign language processing, I actually do not need all patches. If we have 4096 features x 512 frames, we have upwards of 2 million patches. Thus, I was thinking about only using a selection of patches.
For example, here is an image of a frame from a sign language video:
![image](https://github.com/user-attachments/assets/401e036a-64c5-4639-9839-e95e370fecf5)
All I need, in fact, is the areas defined as `Left_Hand`, `Right_Hand`, and `Face_Neck`, assuming I keep the positional information, and possibly a trace around the pose lines, for good measure (green=save, red=discard)
![Paste (1)](https://github.com/user-attachments/assets/e9c7caa4-63dc-4411-8bb7-50705f6605f5)
Makes it so I could save on ~80-90% of the used patches.

3. Right now, I understand I need to run the video through three models: the base model, the pose estimation model, and the segmentation model. Is there a way to reduce it to one model call? I can think about 2, being pose estimation + base model, and select the features based on maybe the bounding box of the hands and face, but if I could use the features maybe from the pose model that would be one call, and make things faster.

**Comment by rawalkhirodkar** [comment]
1. correct. For instance if the embedding dimension is 1536 (Sapiens-1B), the image will be converted to 4096 x 1536 dimension feature.

2. Tiling images is an interesting approach. Are you planning to finetune the model further or use the raw features? Caution: the model was pretrained on natural images (no tiles), in that case finetuning would be recommended. 

Another approach: since the backbone is a transformer, you can also feed the 128 x 128 images, you would need to resize the positional embedding using interpolation. I would expect this to work as well too.

3. We unfortunately as of now do not supported multi-task backbones. Each task has an independent network.

**Comment by AmitMY** [comment]
1. oh wow. 25MB per 1024x1024 frame, that's hefty. 
2. i'd rather go without fine-tuning, so maybe tiling, maybe interpolation
3. cool. so need to run multiple models and then filter the patches. Thanks!
