### ISSUE TITLE
Can I run the lite version on CUDA12.4 device?

### ISSUE THREAD

**Issue by Zeyu-Zhu** [facebookresearch/sapiens#20]
Thanks for the work.

As the doc, the pose estimation is based on mmdet and mmdet is based on mmcv. But in https://mmcv.readthedocs.io/en/latest/get_started/installation.html, there is no suitable version for CUDA12.4.

I'd appreciate it if you can give me some advice?

**Comment by rawalkhirodkar** [comment]
Please follow the full installation instructions in conda.sh
We install from source, so cuda version should not be an issue. 

For lite installation, yes it should run with cuda12.4.

**Comment by fzoric8** [comment]
Hi @rawalkhirodkar, 

Thanks for the info about full installation instructions. 
I've tried to build minimal working `sapiens_lite` env with conda, however without running full install it fails because it says it requires `mmcv==2.0.0rc4` which is not available for the torch 2.2.0. So i suppose that for using `sapiens_lite` I still need to follow full installation instructions in `conda.sh`. 

Thanks for your answer.

**Comment by rawalkhirodkar** [comment]
@fzoric8 for sapiens-lite, mmcv is not a requirement. 

In case of pose estimation inference, you can use 1) any bbox detector of your choice , 2) use mmdet (this requires mmcv, install from source for recent pytorch versions), 3) skip the bbox detection and use the entire image as input.

Let me know if any of this works for you.

**Comment by fzoric8** [comment]
@rawalkhirodkar thank you for the quick response. 

I'll try to do what you suggested. Maybe even without bbox detection. 
Does it work on multiple people or is it just for one person? 

Thanks!

**Comment by rawalkhirodkar** [comment]
@fzoric8 sure thing! pose will work on multiple humans.
