### ISSUE TITLE
Model Compatibility with Lower-Dimension Images

### ISSUE THREAD

**Issue by pooyafayyaz** [facebookresearch/sapiens#52]
First off, thanks for the fantastic work on this project!

I’ve encountered an issue when trying to use the model with lower-dimension images(like 512x512). It seems that everything is being segmented as the background, which in turn affects the depth and normal outputs.

Is there a recommended solution for this? Would using interpolation to upscale the images help, or is there another approach that might be more effective?

![frame_0016](https://github.com/user-attachments/assets/038db030-5a7b-48f8-a82c-0ee21188e4ba)

**Comment by rawalkhirodkar** [comment]
Hello, we are aware of this issue. 
Segmentation model was trained on high resolution data, as a result low resolution are labeled background due to blurry upsampling.

- Option 1: You can try upsampling your image to 1k using super resolution. 
- Option 2: If you have a foreground/background mask, use that in depth and normal prediction. Infact, mask is only needed for depth prediction to normalize depth to 0 to 1. Not needed for normal at all.

We will have an all resolution foreground/background (not body part segmentation) masking model out soon, this will be helpful here.

**Comment by SCZwangxiao** [comment]
> Hello, we are aware of this issue. Segmentation model was trained on high resolution data, as a result low resolution are labeled background due to blurry upsampling.
> 
> * Option 1: You can try upsampling your image to 1k using super resolution.
> * Option 2: If you have a foreground/background mask, use that in depth and normal prediction. Infact, mask is only needed for depth prediction to normalize depth to 0 to 1. Not needed for normal at all.
> 
> We will have an all resolution foreground/background (not body part segmentation) masking model out soon, this will be helpful here.

Would you mind telling us when the low-resolution models will be released?
