### ISSUE TITLE
The model and loaded state dict do not match

### ISSUE THREAD

**Issue by LW-CVer** [facebookresearch/sapiens#75]
![图片](https://github.com/user-attachments/assets/7734d300-8ea8-46cf-8a22-ae6accbc7815)
![图片](https://github.com/user-attachments/assets/884c5bda-4afe-430b-98a6-28d4562cc6e3)

pth: sapiens_0.3b_epoch_1600_clean.pth

**Comment by LW-CVer** [comment]
pretrain/scripts/demo/local/extract_feature.sh

**Comment by rawalkhirodkar** [comment]
@LW-CVer can you share the entire log? This is to check if the model path and config file is consistent.

**Comment by LW-CVer** [comment]
when using "inferencer.model.backbone.out_type = 'featmap"，the output dimsension is (1024,64,64)，without “inferencer.model.backbone.out_type = 'featmap”，the output dimsension is (4097,1024),Why is it 4097, not 4096?

**Comment by LW-CVer** [comment]
> @LW-CVer can you share the entire log? This is to check if the model path and config file is consistent.
I modified "extract_feature.py”，it works now

![图片](https://github.com/user-attachments/assets/87cb425d-7500-4584-97fb-731145a5b8b8)

**Comment by minjung98** [comment]
I also encountered logs indicating that some keys did not match when running `pretrain/scripts/demo/local/extract_feature.sh` with the same model. When I inquired about this, I was informed that the settings were different, leading me to understand that the missing of certain keys was intentional. I would like to ask if my understanding is incorrect, and if, similar to the questioner in this thread, I should modify the code to address the missing key issue.

**Comment by rawalkhirodkar** [comment]
@LW-CVer I assume the issue is resolved on the first screenshot you shared and it looks like you are modifying the inference code.

4097 -> 4096 (num token) + 1 (cls_token). Please not inference without featmap flag is not supported.

**Comment by rawalkhirodkar** [comment]
@minjung98 Please ignore the state_dict mismatch warnings. They occur due to a different schemas we use when pretraining.
