### ISSUE TITLE
The 50 samples of toy dataset

### ISSUE THREAD

**Issue by whitelin0321** [facebookresearch/sapiens#96]
1.We would like to know how the (. npy) data in the normals folder of the Sapiens toy dataset is generated. Some of the data are complete human bodies. Some are just a part of the human body, is this data obtained through cropping? If it is obtained through cutting, what cutting method is used.

2.We obtained the normal dataset through Blender rendering, but we are unsure if it is correct. I compared the data from toy datasets with the data we created as shown in the following figure. On the left are toy datasets, and on the right are the norms data generated from our data. Can you tell us if our data meets the requirements of norms

3. At the same time, we also found that the resolution of the toy datasets you provided is 3072 * 4096. Our data resolution is 1024 * 768. Will the difference in resolution between the two lead to fine tuning the normals model, poor inference results, and blurred details?

![image](https://github.com/user-attachments/assets/a58136a5-6926-44fa-9d67-9c723d1a692a)

**Comment by rawalkhirodkar** [comment]
1. The cropping is due to change in extrinsics and intrinsics of the virtual camera we use in rendering. 
2. It is hard to compare from a single image, on a quick look it looks correct. You want the same coloring scheme in the same camera position. 
3. No, as long as the resolution here is greater than equal to model resolution, you should be ok. Higher resolutions allow for cropping and resizing augmentations which we use.
